# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/python-publish.yml"
      - "pyproject.toml"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.17
      with:
        pypi_token: ${{ secrets.PYPI_T2 }}
